# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DDEV Add-on Registry
baseurl: "/mm-starter"
description: >-
  A registry for DDEV add-ons where users can discover,
  explore, and leave comments on available add-ons.

repository: stasadev/mm-starter

logo: /assets/logo.png
markdown: kramdown

include:
  - _pages

exclude:
  - .bundle/
  - .ddev/
  - .git/
  - .github/
  - .jekyll-cache/
  - .sass-cache/
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

defaults:
  # _addons
  - scope:
      path: '_addons'
    values:
      layout: addon

collections:
  addons:
    output: true
    permalink: /addons/:path
