type: php
docroot: _site
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
hooks:
    post-start:
        - exec: bash -c 'while [ ! -f /var/tmp/bundleinstalldone ]; do sleep 1; done'
        - exec: bash -c 'bundle exec jekyll build --baseurl="" --incremental'
        - exec: echo -e "                                  NOTICE                                        \n
            =================================================================================\n
            =================================================================================\n
            The Jekyll dev container is ready \n LiveReload is available at \e[32m${DDEV_PRIMARY_URL}:4000\e[0m \n
            To troubleshoot any issues run \e[35mddev describe\e[0m or \e[35mddev logs --follow --time\e[0m\n"
omit_containers: [db]
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
web_extra_exposed_ports:
    - name: jekyll
      container_port: 4000
      http_port: 4001
      https_port: 4000
    - name: jekyll-livereload
      container_port: 4010
      http_port: 4011
      https_port: 4010
web_extra_daemons:
    - name: jekyll-dev-daemon
      command: bash -c 'bash .bundle/install && touch /var/tmp/bundleinstalldone && bundle exec jekyll serve --host=0.0.0.0 --baseurl="" --livereload --livereload-port=4010 --incremental'
      directory: /var/www/html
